training_continue:
  model:
    name: unsloth/gemma-3n-E4B-it
    max_seq_length: 1024
    load_in_4bit: true
    load_in_8bit: false
    full_finetuning: false
  lora:
    finetune_vision_layers: false
    finetune_language_layers: true
    finetune_attention_modules: true
    finetune_mlp_modules: true
    target_modules: [q_proj, k_proj, v_proj, o_proj, gate_proj, up_proj, down_proj]
    r: 16
    lora_alpha: 16
    lora_dropout: 0.0
    bias: none
    use_gradient_checkpointing: unsloth
    random_state: 3407
    use_rslora: true
    loftq_config: null
  data:
    dataset_path: dataset/multiturn_expand_all.jsonl
    chat_template: gemma-3
    split_test_size: 0.05
    seed: 42
  trainer:
    dataset_num_proc: 12
    packing: true
    args:
      dataset_text_field: text
      per_device_train_batch_size: 8
      gradient_accumulation_steps: 4
      warmup_ratio: 0.05
      num_train_epochs: 1
      learning_rate: 2.0e-5
      logging_steps: 1
      optim: adamw_8bit
      weight_decay: 0.01
      lr_scheduler_type: cosine
      seed: 3407
      output_dir: outputs
      report_to: tensorboard
      per_device_eval_batch_size: 8
      eval_accumulation_steps: 4
      eval_strategy: steps
      eval_steps: 300
      save_strategy: epoch
      save_total_limit: 1
  generation:
    max_new_tokens: 256
    temperature: 0.7
    top_p: 0.8
    top_k: 20
    do_sample: true
  io:
    instruction_part: "<start_of_turn>user\n"
    response_part: "<start_of_turn>model\n"
  eval_messages:
    - role: system
      content: "你是崩坏星穹铁道的角色流萤，请始终保持角色设定和语气"
    - role: user
      content: "开拓者：流萤，你有什么一直想实现的愿望吗？"

training_finetune:
  model:
    name: checkpoint-3062
    max_seq_length: 1024
    load_in_4bit: true
    load_in_8bit: false
    full_finetuning: false
  lora:
    finetune_vision_layers: false
    finetune_language_layers: true
    finetune_attention_modules: true
    finetune_mlp_modules: true
    target_modules: [q_proj, k_proj, v_proj, o_proj, gate_proj, up_proj, down_proj]
    r: 16
    lora_alpha: 16
    lora_dropout: 0.0
    bias: none
    use_gradient_checkpointing: unsloth
    random_state: 3407
    use_rslora: true
    loftq_config: null
  data:
    dataset_path: firefly_chatml_final.jsonl
    chat_template: gemma-3
  trainer:
    dataset_num_proc: 12
    packing: false
    args:
      dataset_text_field: text
      per_device_train_batch_size: 2
      gradient_accumulation_steps: 4
      warmup_ratio: 0.05
      num_train_epochs: 4
      learning_rate: 2.0e-5
      logging_steps: 1
      optim: adamw_8bit
      weight_decay: 0.01
      lr_scheduler_type: cosine
      seed: 3407
      output_dir: outputs
      report_to: tensorboard
      save_strategy: epoch
      save_total_limit: 4
  generation:
    max_new_tokens: 256
    temperature: 0.7
    top_p: 0.8
    top_k: 20
    do_sample: true
  io:
    instruction_part: "<start_of_turn>user\n"
    response_part: "<start_of_turn>model\n"
  eval_messages:
    - role: system
      content: "你是崩坏星穹铁道的角色流萤，请始终保持角色设定和语气"
    - role: user
      content: "开拓者：流萤，你有什么一直想实现的愿望吗？"

inference:
  model:
    name: unsloth/gemma-3n-E4B-it
    max_seq_length: 4096
    load_in_4bit: true
    full_finetuning: false
  generation:
    max_new_tokens: 4096
    temperature: 1.0
    top_p: 0.95
    top_k: 64
    repetition_penalty: 1.0
    do_sample: true
  device:
    device_map:
      "": cuda:0
  chat:
    system_prompt_key: CONTINUE_LEARN
